.\"
.\" SKEL.1 --Manual page for "skel", a skeleton file expander.
.\"
.TH SKEL 1 "January 2020" "Development Utilities" "The Other Manual"
.SH NAME
skel \- create some files based on a skeleton template
.SH SYNOPSIS
.SY skel
.OP --list
.YS
.SY skel
.OP --name myname
.OP --script filter
.OP --include path:path...
.OP --force
.OP --pascal
.OP --windows
.I skeleton \&.\|.\|.\&
.YS
.SH DESCRIPTION
The
.B skel
command creates one or more files from a skeleton template file.
The skeleeton is a self-extracting shell archive, which is transformed
as it is expanded to replace the word "skeleton" with the specified
.IR name .
The replacement is case sensitive in the following way; if the
replacement name is (e.g.) "foo_bar":
.PP
.RS 2
.PD 0
.TP 14
.B skeleton
is replaced with foo_bar (or fooBar)
.TP
.B Skeleton
is replaced with FooBar
.TP
.B SKELETON
is replaced with FOO_BAR.
.RE
.PD
.PP
Note that this transformation is applied to the shell archive as a
whole, so it applies equally to the files' names and to their
contents.
.PP
The
.I --pascal
option controls whether
.I name
is translated as
.I foo_bar
or
.I fooBar.
.PP
Binary files unpacked by
.B skel
are assumed to be
.BR zip (1)
archives: it applies
.B unzip
to the file, and if that succeeds, it applies the replacement
transformation to the expanded files and then re-zips the files back
into the archive.
This strategy works well for Microsoft Office
files, which are
.B zip
archives of XML documents.
.PP
By default,
.B skel
searches for skeletons in the directory
.IR /usr/local/share/skel.
although this may be overridden by the environment variable
.B SKELPATH
or the
.B --include
command line option, as described below.
.SH OPTIONS
.TP
.BR \-l ,\  \-\-list
List the available skeleton templates.
.TP
.BI \-n\  name
.TQ
.BI \-\-name\fR= name
Modify the generated file names and contents based on
.IR name .
.TP
.BI \-s\  script
.TQ
.BI \-\-script\fR= filter-script
Further modify the generated content by a
script, a simple filter that reads text from
.I stdin
and prints the filtered/modified output to
.IR stdout .
If the environment variable SKEL_FILTER is defined, its value will be used to
name the script.  The script must be named as either an absolute path name, or
name an executable command in PATH.

For example, the script can be used to customise generic copyright
information, using sed:

.EX
#!/usr/bin/env -S sed -f
s/COPYRIGHT/Copyright (c) YEAR AUTHOR/g
s/YEAR/2038/g
s/AUTHOR/Bozo the Clown/g
.EE
.TP
.BI \-I\  path-spec
.TQ
.BI \-\-include\fR= path-spec
Specify the directories to search for skeleton templates, as a colon-separated
list.
.TP
.BR \-p ,\  \-\-pascal
Control expansion of
.I name
to
.IR pascalCase .
.TP
.BR \-f ,\  \-\-force
Force overwriting of existing files when expanding the skeleton template.
.TP
.BR \-w ,\  \-\-windows
Text files are output with Windows format (i.e. <cr><lf>) line endings.
.PD
.SS "Logging Options"
The
.B skel
command specifies its internal logging level in a
.BR syslog (3)
compatible way.  The default logging level is "notice".
The following options set the logging to a specific level.
.PP
.PD 0
.TP 18
.BR \-q ,\  \-\-quiet
Set the logging level to "warning".
.TP
.BR \-v ,\  \-\-verbose
Set the logging level to "info".
.TP
.BR \-_ ,\  \-\-debug
Set the logging level to "debug".
.TP
.BI \-\-log-level\fR= level
Set the logging level to the specified syslog level.
.PD
.SH ENVIRONMENT
.B skel
is sensitive to the following environment variables:
.PD 0
.TP 14
SKELPATH
The default search path for
.B skel
skeleton templates, as a colon-separated list of directories.
.TP
LOG_LEVEL
Specifies the default logging level.
If not defined, the logging level "notice"
is used.
.TP
MIDDENPATH
The search path for additional shell library functions.
.TP
SKEL_FILTER
The name of a filter script to make further changes to the skeleton
.PD
.SH "EXIT STATUS"
.B Skel
exits with the following status:
.PD 0
.TP 4
0
Successfully processed all skeleton templates.
.TP
1
Unable to process all skeleton templates (e.g. cannot open skeleton file).
.TP
2
There was an error in the command line arguments (e.g. unrecognised option).
.SH EXAMPLES
.EX
.B $ skel -l
some output...
.EE
.SH BUGS
The template name transformation is done via a blind
.BR sed ;
there is a possiblility that binary files will be corrupted.
.SH SEE ALSO
.BR shar (1),
.BR sed (1),
.BR zip (1),
.BR logger (1).
